### ISSUE TITLE
[Bug - Front] 게임중 스크롤바 버그 발견

### ISSUE THREAD

**Issue by usanglee** [Hi-Transcendence/ft_transcendence#176]
### ISSUE
게임도중 화면 왼쪽의 스크롤바가 없어졌다 나타났다 반복되는 버그를 발견하였습니다.

https://user-images.githubusercontent.com/40191730/185370600-1af83aa4-1aff-41bb-8f4f-0b1209afa5c6.mov

**Comment by jyhyun97** [comment]
원인은 채팅창에서 보내기 버튼의 css 였고 해결하여 pr 올렸습니다!
