### ISSUE TITLE
[Fix - Front]  Rank 디자인 수정

### ISSUE THREAD

**Issue by dev-samin** [Hi-Transcendence/ft_transcendence#201]
### ISSUE
 * Type: `fix`
 * Detail: Rank 디자인 수정
 ### TODO
- [x] 배경 색 변경
- [x] 페이지 크리 변경
- [x] 랭킹 리스트 요소 디자인
- [x] 스크롤 방식으로 변경

**Comment by jyhyun97** [comment]
스크롤은 기존에 구현이 되어있었습니다.
